# Generated by Django 6.0.5 on 2026-05-24 11:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmissionRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SAP_FUEL", "SAP Fuel"),
                            ("SAP_PROCUREMENT", "SAP Procurement"),
                            ("UTILITY_ELECTRICITY", "Utility Electricity"),
                            ("CORPORATE_TRAVEL", "Corporate Travel"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "source_location_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "source_location_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SAP_PLANT", "SAP Plant"),
                            ("UTILITY_METER", "Utility Meter"),
                            ("AIRPORT", "Airport"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("raw_data", models.JSONField()),
                ("raw_value", models.DecimalField(decimal_places=4, max_digits=15)),
                ("raw_unit", models.CharField(max_length=30)),
                (
                    "normalized_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "normalized_unit",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "conversion_factor",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "conversion_factor_source",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "scope",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SCOPE_1", "Scope 1"),
                            ("SCOPE_2_LOCATION", "Scope 2 (Location-Based)"),
                            ("SCOPE_3", "Scope 3"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("FLAGGED", "Flagged"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                (
                    "flag_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MISSING_FIELD", "Missing Required Field"),
                            ("VALUE_OUT_OF_RANGE", "Value Out of Range"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("flag_reason", models.TextField(blank=True, null=True)),
                ("flag_score", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SAP_FUEL", "SAP Fuel"),
                            ("SAP_PROCUREMENT", "SAP Procurement"),
                            ("UTILITY_ELECTRICITY", "Utility Electricity"),
                            ("CORPORATE_TRAVEL", "Corporate Travel"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("rows_total", models.IntegerField(default=0)),
                ("rows_succeeded", models.IntegerField(default=0)),
                ("rows_failed", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADING", "Uploading"),
                            ("VALIDATING", "Validating"),
                            ("IMPORTED", "Imported"),
                            ("REVIEW_IN_PROGRESS", "Review In Progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="UPLOADING",
                        max_length=30,
                    ),
                ),
                (
                    "total_kgCO2_scope1",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "total_kgCO2_scope2_location",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "total_kgCO2_scope3",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "imported_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "ordering": ["-imported_at"],
            },
        ),
        migrations.CreateModel(
            name="DataFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SAP_FUEL", "SAP Fuel"),
                            ("SAP_PROCUREMENT", "SAP Procurement"),
                            ("UTILITY_ELECTRICITY", "Utility Electricity"),
                            ("CORPORATE_TRAVEL", "Corporate Travel"),
                        ],
                        max_length=30,
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("MIN_VALUE", "Minimum Value"),
                            ("MAX_VALUE", "Maximum Value"),
                            ("REQUIRED", "Required Field"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "threshold_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "unique_together": {("source_type", "field_name", "rule_type")},
            },
        ),
        migrations.CreateModel(
            name="ApprovalLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("APPROVED", "Approved"),
                            ("FLAGGED", "Flagged"),
                            ("REJECTED", "Rejected"),
                            ("NOTE_ADDED", "Note Added"),
                        ],
                        max_length=20,
                    ),
                ),
                ("performed_by", models.CharField(default="analyst", max_length=100)),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_history",
                        to="core.emissionrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["performed_at"],
            },
        ),
        migrations.AddField(
            model_name="emissionrecord",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="core.importbatch",
            ),
        ),
    ]
